# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69cb2f23264c4180cda5057ce7660c5da0094ff8ee8dc31b5e10c6de9c368128492a8b6ebae964302d5d85a19f84dd1f1fb6f258c8035bf7a0e739f17236598f

test:
  secret_key_base: 80450156b4c3b22aebd68642d39c42d293e1bef997222cec2b4274ca2274df05380dc2ecb2e51e00fe9f129a6f26644fd0593f38331d508074a867ce691c4361

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
